# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program5.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 0, 201, 101))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 90, 261, 121))
        self.label_3.setObjectName("label_3")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setGeometry(QtCore.QRect(40, 210, 91, 21))
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setGeometry(QtCore.QRect(340, 210, 81, 16))
        self.label_y.setObjectName("label_y")
        self.label_z = QtWidgets.QLabel(self.centralwidget)
        self.label_z.setGeometry(QtCore.QRect(590, 210, 81, 16))
        self.label_z.setObjectName("label_z")
        self.Button_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.Button_calcular.setGeometry(QtCore.QRect(330, 290, 113, 32))
        self.Button_calcular.setObjectName("Button_calcular")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(350, 340, 60, 16))
        self.label_resultado.setObjectName("label_resultado")
        self.button_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.button_limpiar.setGeometry(QtCore.QRect(140, 420, 113, 32))
        self.button_limpiar.setObjectName("button_limpiar")
        self.button_salir = QtWidgets.QPushButton(self.centralwidget)
        self.button_salir.setGeometry(QtCore.QRect(540, 420, 113, 32))
        self.button_salir.setObjectName("button_salir")
        self.text_x = QtWidgets.QTextEdit(self.centralwidget)
        self.text_x.setGeometry(QtCore.QRect(30, 240, 121, 31))
        self.text_x.setObjectName("text_x")
        self.text_y = QtWidgets.QTextEdit(self.centralwidget)
        self.text_y.setGeometry(QtCore.QRect(290, 240, 161, 31))
        self.text_y.setObjectName("text_y")
        self.text_z = QtWidgets.QTextEdit(self.centralwidget)
        self.text_z.setGeometry(QtCore.QRect(540, 240, 161, 31))
        self.text_z.setObjectName("text_z")
        self.text_resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.text_resultado.setGeometry(QtCore.QRect(280, 360, 201, 41))
        self.text_resultado.setObjectName("text_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/prefixbp5/Captura de Pantalla 2021-12-02 a la(s) 23.52.01.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/prefixtnm5/Captura de Pantalla 2021-12-02 a la(s) 23.34.10.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Evaluando la expresion.</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">       r= </span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">(3x</span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; vertical-align:super;\">4</span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">+2xy</span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; vertical-align:super;\">2</span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">z)</span><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; vertical-align:super;\">1/2 </span><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\"/><span style=\" font-size:18pt; font-weight:600;\">+ 5x</span><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\">2</span><span style=\" font-size:18pt; font-weight:600;\">y</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\"/><span style=\" font-size:18pt; font-weight:600;\">3+x</span><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\">2</span><span style=\" font-size:18pt; font-weight:600;\">y</span><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\">2</span><span style=\" font-size:18pt; font-weight:600;\">z</span><span style=\" font-size:18pt; font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.label_x.setText(_translate("MainWindow", "Valor para X"))
        self.label_y.setText(_translate("MainWindow", "valor para y"))
        self.label_z.setText(_translate("MainWindow", "Valor para z"))
        self.Button_calcular.setText(_translate("MainWindow", "Calcular"))
        self.label_resultado.setText(_translate("MainWindow", "Resultado"))
        self.button_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.button_salir.setText(_translate("MainWindow", "Salir"))
import imagebp5_rc
import imagetnm5_rc
